# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{polyglot}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guilherme Cirne"]
  s.date = %q{2010-04-19}
  s.description = %q{Description}
  s.email = %q{gcirne@gmail.com}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
     "License.txt",
     "Manifest.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "config/hoe.rb",
     "config/requirements.rb",
     "lib/polyglot.rb",
     "lib/polyglot/version.rb",
     "log/debug.log",
     "script/destroy",
     "script/generate",
     "script/txt2html",
     "tasks/deployment.rake",
     "tasks/environment.rake",
     "tasks/website.rake",
     "test/test_helper.rb",
     "test/test_polyglot.rb",
     "website/index.html",
     "website/index.txt",
     "website/javascripts/rounded_corners_lite.inc.js",
     "website/stylesheets/screen.css",
     "website/template.rhtml"
  ]
  s.homepage = %q{http://github.com/gcirne/polyglot}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/test_helper.rb",
     "test/test_polyglot.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

